### PR TITLE
Update Inline code

### PR DESCRIPTION
**Pull request by marble**
* Add `bash` and `shell` textroles for `code`
* Improve color contrast for all inline styles derived from `code`

### CODE REVIEW

**Comment by marble** [comment]
The changes will really be visible only with the next version of the sphinx_typo3_theme, which will come with the next DRC (Docker Rendering Container)

**Comment by alexander-nitsche** [comment]
hi martin, i would remove the `:shell:` text role again as the use case is a duplicate of that of `:bash:`. greetings, alex

fyi: in the current standardization run i replace all shell occurrences with bash.

**Comment by linawolf** [comment]
I would support this PR as bash is a special case of a shell, the  Bourne-again shell. therefore `:shell:` is more generic then `:bash:`

**Comment by alexander-nitsche** [comment]
putting my considerations in other words: with `bash` text role only the documentation writer immediately knows what text role to choose for his or her shell and bash code. with `bash` and `shell` text roles the writer looses this certainty and we will gain nothing.

**Review by linawolf — APPROVED** [review]

**Pull request merged**
