### PR TITLE
[TASK] Remove Hint

### PR DESCRIPTION
**Pull request by linawolf**
The same information is already contained in the general disclaimer

### CODE REVIEW

**Review by brotkrueml — COMMENTED** [review]
Where can I find the "general container"?

**Comment by linawolf** [comment]
Index.rst.txt

**Comment by linawolf** [comment]
Or just look at it rendered: https://docs.typo3.org/m/typo3/docs-how-to-document/main/en-us/WritingDocForExtension/Index.html

**Comment by brotkrueml** [comment]
Hmm, I suggest to leave it as is: We link directly from "docs.typo3.org > Developing and using extensions > Document an extension" to this page. So this information might get lost as users won't mostly navigation to the start page from this page.

**Comment by linawolf** [comment]
The Disclaimer is displayed on top of EVERY page

**Review by Alagts — APPROVED** [review]

**Pull request merged**
