### PR TITLE
[TASK] Drop the appendix

### PR DESCRIPTION
**Pull request by linawolf**
There is no more usefull information in here.

### CODE REVIEW

**Review by brotkrueml — COMMENTED** [review]
Shouldn't this go to main as this is unrelated to the PHP-based rendering?

**Comment by linawolf** [comment]
I thought to generally overhaul the guide and then do a switch. I don't think we should maintain two different versions..

**Comment by brotkrueml** [comment]
> I thought to generally overhaul the guide and then do a switch. I don't think we should maintain two different versions..

Provide a PR against main branch, it gets merged, rebase documentation-draft.

**Comment by linawolf** [comment]
See https://github.com/TYPO3-Documentation/TYPO3CMS-Guide-HowToDocument/pull/358

**Pull request closed without merging**
